# Generated by kankyo. Do not edit by hand.
from __future__ import annotations

from pathlib import Path
from kankyo import Secret
from typing import Literal
from datetime import timedelta
from typing import cast as _cast
from collections.abc import Mapping
from dataclasses import dataclass as _dataclass
from kankyo import load_environment as _load_environment
from kankyo import Rule as _Rule, Field as _Field, Schema as _Schema

_schema = _Schema(
    database_url=_Field('DATABASE_URL', _Rule('url', schemes=('postgres', 'postgresql')), aliases=('DB_URL',)),
    port=_Field('PORT', _Rule('integer', minimum=1, maximum=65535), description='HTTP listen port.', default='8080'),
    debug=_Field('DEBUG', _Rule('boolean'), optional=True),
    request_timeout=_Field('REQUEST_TIMEOUT', _Rule('duration'), default='5'),
    allowed_hosts=_Field('ALLOWED_HOSTS', _Rule('list', item=_Rule('string', min_length=1), unique=True), default='["localhost"]'),
    log_level=_Field('LOG_LEVEL', _Rule('one_of', choices=('debug', 'info', 'warning', 'error')), default='info'),
    api_token=_Field('API_TOKEN', _Rule('secret', min_length=1)),
)

@_dataclass(frozen=True, slots=True, kw_only=True)
class Config:
    """Validated application configuration."""
    database_url: str
    # HTTP listen port.
    port: int
    debug: bool | None
    request_timeout: timedelta
    allowed_hosts: list[str]
    log_level: Literal['debug', 'info', 'warning', 'error']
    api_token: Secret

def load_from(source: Mapping[str, str]) -> Config:
    """Load only the supplied values, without reading files or the process environment."""
    values = _schema.load(source)
    return Config(
        database_url=_cast(str, values['database_url']),
        port=_cast(int, values['port']),
        debug=_cast(bool | None, values['debug']),
        request_timeout=_cast(timedelta, values['request_timeout']),
        allowed_hosts=_cast(list[str], values['allowed_hosts']),
        log_level=_cast(Literal['debug', 'info', 'warning', 'error'], values['log_level']),
        api_token=_cast(Secret, values['api_token']),
    )

def load(*, root: str | Path = '.', environment: str | None = None,
         overrides: Mapping[str, str] | None = None) -> Config:
    """Load dotenv layers, process variables, and explicit overrides."""
    return load_from(_load_environment(root=root, environment=environment, overrides=overrides))
