from __future__ import annotations

from os import replace
from pathlib import Path
from runpy import run_path
from decimal import Decimal
from kankyo.rules import Rule
from dataclasses import fields
from sys import path as sys_path
from tempfile import NamedTemporaryFile
from kankyo.errors import SchemaError, GenerationError
from kankyo.schema import Field, Schema, valid_identifier

_HEADER = '# Generated by kankyo. Do not edit by hand.\n'
_TYPES = {'string': 'str', 'integer': 'int', 'number': 'float', 'boolean': 'bool', 'decimal': 'Decimal',
          'duration': 'timedelta', 'path': 'Path', 'url': 'str', 'uuid': 'UUID',
          'ip_address': 'IPv4Address | IPv6Address', 'secret': 'Secret'}
_IMPORTS = {'Decimal': 'from decimal import Decimal', 'timedelta': 'from datetime import timedelta',
            'UUID': 'from uuid import UUID', 'IPv4Address | IPv6Address': 'from ipaddress import IPv4Address, IPv6Address',
            'Secret': 'from kankyo import Secret'}
_RESERVED = {'str', 'int', 'float', 'bool', 'list', 'Decimal', 'timedelta', 'Path', 'UUID', 'IPv4Address',
             'IPv6Address', 'Secret', 'Literal', 'Mapping', 'load', 'load_from', 'source', 'values'}

def _annotation(rule: Rule, imports: set[str]) -> str:
    if rule.kind == 'list':
        assert rule.item is not None
        return f'list[{_annotation(rule.item, imports)}]'
    if rule.kind == 'one_of':
        imports.add('from typing import Literal')
        return 'Literal[' + ', '.join(repr(choice) for choice in rule.choices) + ']'

    annotation = _TYPES[rule.kind]
    if annotation in _IMPORTS:
        imports.add(_IMPORTS[annotation])

    return annotation

def _literal(value: object, imports: set[str]) -> str:
    if isinstance(value, Rule):
        return _rule_source(value, imports)
    if isinstance(value, Decimal):
        imports.add(_IMPORTS['Decimal'])
        return f'Decimal({str(value)!r})'

    return repr(value)

def _rule_source(rule: Rule, imports: set[str]) -> str:
    arguments = [repr(rule.kind)]
    for field in fields(rule):
        value = getattr(rule, field.name)
        if field.name != 'kind' and value != field.default:
            arguments.append(f'{field.name}={_literal(value, imports)}')

    return '_Rule(' + ', '.join(arguments) + ')'

def _field_source(field: Field, imports: set[str]) -> str:
    arguments = [repr(field.variable), _rule_source(field.rule, imports)]
    if field.optional:
        arguments.append('optional=True')
    if field.aliases:
        arguments.append(f'aliases={field.aliases!r}')
    if field.description:
        arguments.append(f'description={field.description!r}')
    if field.default is not None:
        arguments.append(f'default={field.default!r}')

    return '_Field(' + ', '.join(arguments) + ')'

def load_schema(file: str | Path, *, name: str | None = None) -> Schema:
    """Execute a trusted Python schema file and select its Schema instance."""
    schema_path = Path(file).resolve()
    if schema_path.suffix != '.py' or not schema_path.is_file():
        raise GenerationError(f'Schema must be an existing Python file: {schema_path}')

    previous_path = sys_path[:]
    try:
        sys_path.insert(0, str(schema_path.parent))
        namespace = run_path(str(schema_path), run_name='_kankyo_schema_')
    except Exception as exc:
        if isinstance(exc, SchemaError):
            raise GenerationError(f'Invalid schema: {exc}') from None

        raise GenerationError(f'Could not execute {schema_path.name} ({type(exc).__name__})') from None
    finally:
        sys_path[:] = previous_path

    if name is not None:
        selected = namespace.get(name)
        if not isinstance(selected, Schema):
            raise GenerationError(f'{name!r} is not a Schema in {schema_path.name}')

        return selected

    schemas = {key: value for key, value in namespace.items() if isinstance(value, Schema) and not key.startswith('_')}
    if len(schemas) != 1:
        raise GenerationError('Expected one public Schema instance; select one with --name')

    return next(iter(schemas.values()))

def render(schema: Schema, *, class_name: str = 'Config') -> str:
    """Render deterministic Python source with concrete field annotations."""
    if not valid_identifier(class_name) or class_name in _RESERVED:
        raise GenerationError(f'Invalid or reserved client class name: {class_name!r}')

    imports = {'from pathlib import Path', 'from typing import cast as _cast',
               'from dataclasses import dataclass as _dataclass', 'from collections.abc import Mapping',
               'from kankyo import Rule as _Rule, Field as _Field, Schema as _Schema',
               'from kankyo import load_environment as _load_environment'}
    annotations = {}
    schema_lines = ['_schema = _Schema(']
    for name, field in schema.fields.items():
        annotation = _annotation(field.rule, imports)
        if field.optional and field.default is None:
            annotation += ' | None'
        annotations[name] = annotation
        schema_lines.append(f'    {name}={_field_source(field, imports)},')
    schema_lines.append(')')

    body = ['@_dataclass(frozen=True, slots=True, kw_only=True)', f'class {class_name}:',
            '    """Validated application configuration."""']
    for name, field in schema.fields.items():
        if field.description:
            body.extend('    # ' + line.replace('\0', r'\0') for line in field.description.splitlines())
        body.append(f'    {name}: {annotations[name]}')

    body.extend(['', f'def load_from(source: Mapping[str, str]) -> {class_name}:',
                 '    """Load only the supplied values, without reading files or the process environment."""',
                 '    values = _schema.load(source)', f'    return {class_name}('])
    for name, annotation in annotations.items():
        body.append(f'        {name}=_cast({annotation}, values[{name!r}]),')
    body.extend(['    )', '',
                 "def load(*, root: str | Path = '.', environment: str | None = None,",
                 f'         overrides: Mapping[str, str] | None = None) -> {class_name}:',
                 '    """Load dotenv layers, process variables, and explicit overrides."""',
                 '    return load_from(_load_environment(root=root, environment=environment, overrides=overrides))'])

    source = _HEADER + 'from __future__ import annotations\n\n'
    source += '\n'.join(sorted(imports, key=lambda statement: (len(statement), statement))) + '\n\n'
    source += '\n'.join(schema_lines) + '\n\n' + '\n'.join(body) + '\n'
    compile(source, '<generated kankyo client>', 'exec')
    return source

def generate(file: str | Path, *, output: str | Path | None = None, name: str | None = None,
             class_name: str = 'Config', check: bool = False, force: bool = False) -> Path:
    """Generate atomically, or check freshness without changing any files."""
    schema_path = Path(file).resolve()
    target = Path(output).resolve() if output is not None else schema_path.with_name('config_gen.py')
    if target == schema_path or (target.exists() and schema_path.exists() and target.samefile(schema_path)):
        raise GenerationError('The output must not overwrite the schema file')
    if target.suffix != '.py':
        raise GenerationError('The output must be a .py file')

    source = render(load_schema(schema_path, name=name), class_name=class_name)
    existing = target.read_text(encoding='utf-8') if target.exists() else None
    if check:
        if existing != source:
            raise GenerationError(f'Generated client is missing or out of date: {target}')

        return target

    if existing == source:
        return target
    if existing is not None and not existing.startswith(_HEADER) and not force:
        raise GenerationError(f'Refusing to overwrite a file not generated by kankyo: {target}; use --force to replace it')

    target.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n', dir=target.parent, delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(source)
        replace(temporary, target)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)

    return target
